### ISSUE TITLE
commands to a real Mochad server buffer up and do not execute immediately

### ISSUE THREAD

**Issue by clach04** [clach04/x10_any#1]
Reported in https://github.com/clach04/home-assistant-x10/issues/1

Suspect this is due to `\n` rather than `\r` usage, https://github.com/zonyl/pytomation/blob/master/pytomation/interfaces/mochad.py#L151 is using 0x0d as teminator. x10_any has only been tested with a fake server so far.

**Comment by clach04** [comment]
Proposed fix:

```
diff --git a/x10_any/__init__.py b/x10_any/__init__.py
index 7660c06..fbcc74b 100644
--- a/x10_any/__init__.py
+++ b/x10_any/__init__.py
@@ -240,7 +240,7 @@ class MochadDriver(X10Driver):
         house_and_unit = to_bytes(house_and_unit)
         # TODO normalize/validate state
         state = to_bytes(state)
-        mochad_cmd = self.default_type + b' ' + house_and_unit + b' ' + state + b'\n'  # byte concat works with older Python 3.4
+        mochad_cmd = self.default_type + b' ' + house_and_unit + b' ' + state + b'\r'  # byte concat works with older Python 3.4
         log.debug('mochad send: %r', mochad_cmd)
         mochad_host, mochad_port = self.device_address
         result = netcat(mochad_host, mochad_port, mochad_cmd)
```

**Comment by clach04** [comment]
The source code for Mochad, in `encode.c:837` `cm15a_encode()` appear to check for either `\r` or `\n` (it also checks for end-of-string), the behavior reported in https://github.com/clach04/home-assistant-x10/issues/1#issuecomment-233545467 implies that is not working.
- Many of the code samples for Mochad (including the Python tk demo) only use `\n`
  - however the Perl code sample explicitly uses `\r`.
- hautomation_x10 sends `\n\n` - see https://github.com/jpardobl/hautomation_x10/blob/master/hautomation_x10/cmds.py#L19 and https://github.com/jpardobl/hautomation_x10/blob/master/hautomation_x10/driver.py#L22
- pytomation uses `\r` (well the byte literal `\x0D` which is the same thing) https://github.com/zonyl/pytomation/blob/master/pytomation/interfaces/mochad.py#L151
- netcat `nc` (at least the default one Ubuntu uses which is the BSD implementation) when used with `echo` only uses `\n` - proved with a listen mode of `nc -l 1099 | od -c`
- telnet uses the sequence `\r\n` (confirmed using nc listen mode) as expected and as that works for the original reported Mochad server this seems to be the way to go. Using this also works with the current version of https://bitbucket.org/clach04/mochad_firecracker

**Comment by clach04** [comment]
@akeshan  can you try the current version from git please? Example test.

```
import x10_any

x10_any.default_logger.setLevel(x10_any.logging.DEBUG) # DEBUG

dev = x10_any.MochadDriver()
dev.x10_command('B', 4, x10_any.ON)
dev.x10_command('B', 4, x10_any.OFF)
```

Thanks.

**Comment by akeshan** [comment]
Tried the latest version and it works great, very responsive.

**Comment by clach04** [comment]
@akeshan many thanks for your assistance with this, https://pypi.python.org/pypi/x10_any/0.0.6 now posted and should be pip installable and working.
